const test=require('node:test');const assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../add-on.js'),'utf8');
function boot(api,config={enableSuppliesOrders:true}){const dom=new JSDOM('<body/>',{url:'https://sandbox.elabjournal.com/',runScripts:'outside-only'}),w=dom.window;w.eLabSDK={API:{call:api}};w.eval(source);w.greenchemistry_ai.init(config);return w;}
const tick=()=>new Promise(r=>setImmediate(r));const click=(w,label)=>[...w.document.querySelectorAll('button')].find(x=>x.textContent===label).click();
async function order(w){await w.greenchemistry_ai.openSupplyOrder();const inputs=w.document.querySelectorAll('input');inputs[0].value='Ethanol';inputs[1].value='3';inputs[2].value='2';click(w,'Search catalog');await tick();click(w,'Select');click(w,'Place pending order');click(w,'Confirm order');await tick();}
test('catalog shows product number, supplier, and package size before confirmation',async()=>{const w=boot(r=>r.onSuccess(null,200,{data:[{catalogItemID:9,name:'Ethanol',catalogNumber:'SKU-9',supplierID:2,amount:500,quantityType:'mL'}]}));await w.greenchemistry_ai.openSupplyOrder();w.document.querySelector('input').value='Ethanol';click(w,'Search catalog');await tick();assert.match(w.document.body.textContent,/SKU-9/);assert.match(w.document.body.textContent,/500 mL/);click(w,'Select');click(w,'Place pending order');assert.match(w.document.body.textContent,/SKU-9/);});
test('readback finds exact returned ID on a later page',async()=>{let pages=[];const w=boot(r=>{if(r.path==='supplies/catalogitems')r.onSuccess(null,200,{data:[{catalogItemID:9,name:'Ethanol'}]});else if(r.method==='POST')r.onSuccess(null,200,44);else {pages.push(r.params.$page);r.onSuccess(null,200,r.params.$page===0?{data:[{shoppingItemID:99,sampleID:3,catalogItemID:9,amount:2,status:'PENDING'}],hasNextPage:true}:{data:[{shoppingItemID:44,sampleID:3,catalogItemID:9,amount:2,status:'PENDING'}],hasNextPage:false});}});await order(w);assert.deepEqual(pages,[0,1]);assert.match(w.document.body.textContent,/Order 44 verified/);});
test('mismatched readback retains created ID and locks any new attempt',async()=>{let posts=0;const w=boot(r=>{if(r.path==='supplies/catalogitems')r.onSuccess(null,200,{data:[{catalogItemID:9,name:'Ethanol'}]});else if(r.method==='POST'){posts++;r.onSuccess(null,200,44);}else r.onSuccess(null,200,{data:[{shoppingItemID:44,sampleID:999,catalogItemID:9,amount:2,status:'PENDING'}],hasNextPage:false});});await order(w);assert.match(w.document.body.textContent,/uncertain.*created ID 44/);assert.doesNotMatch(w.document.body.textContent,/Order 44 verified/);await w.greenchemistry_ai.openSupplyOrder();assert.match(w.document.body.textContent,/44/);assert.match(w.document.body.textContent,/locked/);assert.equal(posts,1);});
test('clipboard failure provides manual-copy fallback without any GCai opening',async()=>{const w=boot(()=>{});let opens=0;w.open=()=>{opens++;};w.navigator.clipboard={writeText:()=>Promise.reject(new Error('denied'))};await assert.rejects(w.greenchemistry_ai.openGCaiAfterCopy('Text'),/denied|Clipboard/);assert.equal(opens,0);});
