-- Idempotent resource registration for the iGAL 2.0 article and its supporting information.
-- Apply with the Supabase service role after the literature migrations are installed.
INSERT INTO literature_source_documents
  (id, doi, title, journal, volume, year, source_pdf, source_checksum, rights_status, document_type, visibility, metadata)
VALUES
('sc1c01940','10.1021/acssuschemeng.1c01940','Improved iGAL 2.0 Metric Empowers Pharmaceutical Scientists to Make Meaningful Contributions to United Nations Sustainable Development Goal 12','ACS Sustainable Chemistry & Engineering',10,2022,'https://pubs.acs.org/doi/pdf/10.1021/acssuschemeng.1c01940','f767209b8884750de46a1f62ab1cf80175418219b40675fa410cd7ff81b21c12','user_supplied_pdf_rights_unverified','research_article','public','{"canonical_url":"https://doi.org/10.1021/acssuschemeng.1c01940","pages":15,"extraction_method":"PyMuPDF","extraction_characters":72932,"local_artifact":"/Users/ct-mac-mini/.hermes/cache/documents/doc_317f4a633f9f_sc1c01940.pdf","related_source_id":"sc1c01940","access_note":"User-supplied PDF retained for internal evidence processing; publisher rights/reuse status not independently verified.","topics":["iGAL 2.0","relative process greenness","process mass intensity","complete E factor","yield","convergence","API manufacturing","CASP","SDG 12"]}'::jsonb),
('sc1c01940_si_001','10.1021/acssuschemeng.1c01940','Supporting Information for Improved iGAL 2.0 Metric Empowers Pharmaceutical Scientists to Make Meaningful Contributions to United Nations Sustainable Development Goal 12','ACS Sustainable Chemistry & Engineering',10,2022,'https://pubs.acs.org/doi/suppl/10.1021/acssuschemeng.1c01940/suppl_file/sc1c01940_si_001.pdf','c1ece63e4165cc32e5b7225e5be856c9d8ce239caebc5eb3a6a291db43b64b92','user_supplied_pdf_rights_unverified','supporting_information','public','{"canonical_url":"https://doi.org/10.1021/acssuschemeng.1c01940","pages":41,"extraction_method":"PyMuPDF","extraction_characters":44215,"local_artifact":"/Users/ct-mac-mini/.hermes/cache/documents/doc_fea8bc214b0e_sc1c01940_si_001.pdf","related_source_id":"sc1c01940","access_note":"User-supplied PDF retained for internal evidence processing; publisher rights/reuse status not independently verified.","topics":["iGAL 2.0","relative process greenness","process mass intensity","complete E factor","yield","convergence","API manufacturing","CASP","SDG 12"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  doi=EXCLUDED.doi, title=EXCLUDED.title, journal=EXCLUDED.journal, volume=EXCLUDED.volume, year=EXCLUDED.year,
  source_pdf=EXCLUDED.source_pdf, source_checksum=EXCLUDED.source_checksum, rights_status=EXCLUDED.rights_status,
  document_type=EXCLUDED.document_type, visibility=EXCLUDED.visibility, metadata=EXCLUDED.metadata, updated_at=now();
